name: PR-Greeting
on:
  pull_request:
    types: [opened]


jobs:
    build-site:
        runs-on: ubuntu-latest
        steps:
        - name: see payload
          run: |
            echo "FULL PAYLOAD:\n${PAYLOAD}\n"
            echo "PR_PAYLOAD PAYLOAD:\n${PR_PAYLOAD}"
          env:
            PAYLOAD: ${{ toJSON(github.event) }}
            PR_PAYLOAD: ${{ github.event.pull_request }}

        - name: greeting
          uses: actions/first-interaction@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            pr-message: "Hello, thank you for contributing to `fastpages`! If you haven't already, it might be helpful to read our [contributing guide](https://github.com/fastai/fastpages/blob/master/CONTRIBUTING.md).  Additionally, the `fastpages` repo is equipped with automated tests that can aid in reviewing PRs.  You can generate a preview of how the blog will look with your proposed changes by making a comment on this PR containing the magic command `/preview` (you can use this command multiple times, if needed).  Please use this to ensure that your site looks reasonable before requesting a review."
